name: Deploy Next.js App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./lukaspop
          file: ./lukaspop/Dockerfile
          push: false
          tags: lukaspop:latest

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/pop/personal-website
            git config --global --add safe.directory /home/pop/personal-website
            git pull
            cd lukaspop
            docker compose up -d --build
